name: aws_amplify_test
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  amplify_auth_cognito: ^1.0.1
  amplify_flutter: ^1.0.1
  amplify_api: ^1.0.1
#  amplify_auth_cognito: ^0.6.0
  amplify_authenticator: ^1.0.0
  amplify_datastore: ^1.0.1
#  amplify_flutter: ^0.6.0
  amplify_storage_s3: ^1.0.1
  cached_network_image: ^3.2.1
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  flutter_riverpod: ^1.0.4
  hooks_riverpod: ^1.0.4
  image_picker: ^0.8.5+3
  intl: ^0.18.0
  go_router: ^7.1.1
  equatable: ^2.0.5

dev_dependencies:
  amplify_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/amplify.png